linters:
  LineLength:
    max: 180
    exclude:
      - app/views/layouts/_moj_logo.html.haml
      - app/views/layouts/_footer_crown.html.haml
      - app/views/shared/_alert.html.haml
  ViewLength:
    max: 200
