require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6
  Exclude:
    - tmp/**/*
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/spring
    - bin/yarn
    - bin/webpack
    - bin/webpack-dev-server
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - spec/spec_helpers.rb
    - spec/rails_helper.rb
    - node_modules/**/*

Capybara/FeatureMethods:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['(\A|\s)#','.*\s+ # .*', "body: '{\".*\":"]
  AllowHeredoc: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - config/routes.rb

Metrics/MethodLength:
  Max: 15

# => Rails
Rails/FilePath:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

# => RSpec
RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*

RSpec/NestedGroups:
  Max: 4

# => Style
Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/users/*controller.rb

Style/RegexpLiteral:
  EnforcedStyle: slashes
