inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.1
  TargetRailsVersion: 6
  Exclude:
    - tmp/**/*
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/spring
    - bin/yarn
    - bin/webpack
    - bin/webpack-dev-server
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - spec/spec_helpers.rb
    - spec/rails_helper.rb
    - node_modules/**/*

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 110
  AllowedPatterns: ['(\A|\s)#', '.*\s+ # .*', 'body: ''{".*":', "%r{http.*"]
  AllowHeredoc: true

Layout/RedundantLineBreak:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - app/models/ability.rb
    - spec/features/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - config/routes.rb
    - config/environments/*.rb
    - config/initializers/devise.rb

Metrics/MethodLength:
  Max: 15

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SelectMap:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

# => Rails
#new
Rails/ActionControllerFlashBeforeRender: # 4 errors
  Enabled: false

Rails/EnvironmentVariableAccess:
  AllowReads: true

Rails/FilePath:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Exclude:
    - app/models/cd_api/*

Rails/HelperInstanceVariable:
  Exclude:
    - app/helpers/hearing_paginator.rb

Rails/OutputSafety:
  Exclude:
    - lib/gds_design_system_breadcrumb_builder.rb

Rails/RequestReferer:
  EnforcedStyle: referrer

# => RSpec
RSpec/AnyInstance:
  Enabled: false

RSpec/Dialect:
  PreferredMethods: ["feature", "scenario"]

RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NestedGroups:
  Max: 4

RSpec/NoExpectationExample:
  Exclude:
    - spec/features/unlinked_defendant_flow_spec.rb
    - spec/features/breadcrumbs_spec.rb

RSpec/Rails/InferredSpecType: #122 errors
  Enabled: false

RSpec/SortMetadata: #38 errors
  Enabled: false

# => Style
Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FormatStringToken:
  Exclude:
    - app/models/search.rb

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/users/*controller.rb

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RegexpLiteral:
  EnforcedStyle: slashes

Style/SlicingWithRange:
  Enabled: true

Style/OpenStructUse:
  Enabled: true

Rails/I18nLocaleTexts:
  Exclude:
    - spec/**/*.rb

RSpec/VerifiedDoubleReference:
  Enabled: false

Style/RedundantStringEscape:
  Exclude: 
    - app/services/cd_api/reference_parser_service.rb
