inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

# There would be no value in going through and
# updating the code base to remove these, so we will disable these cops.
RSpec/LeadingSubject:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
