require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6
  Exclude:
    - tmp/**/*
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/spring
    - bin/yarn
    - bin/webpack
    - bin/webpack-dev-server
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - spec/spec_helpers.rb
    - spec/rails_helper.rb
    - node_modules/**/*

Capybara/FeatureMethods:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: true

Layout/LineLength:
  Max: 110
  IgnoredPatterns: ['(\A|\s)#','.*\s+ # .*', "body: '{\".*\":", "%r{http.*"]
  AllowHeredoc: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - app/models/ability.rb
    - spec/features/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - config/routes.rb
    - config/initializers/devise.rb

Metrics/MethodLength:
  Max: 15

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

# => Rails
Rails/FilePath:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - lib/gds_design_system_breadcrumb_builder.rb

RSpec/AnyInstance:
  Enabled: false

# => RSpec
RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*

RSpec/NestedGroups:
  Max: 4

# => Style
Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FormatStringToken:
  Exclude:
    - app/models/search.rb

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/users/*controller.rb

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RegexpLiteral:
  EnforcedStyle: slashes

Style/SlicingWithRange:
  Enabled: true
