apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "laa-court-data-ui.fullName" . }}-app-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laa-court-data-ui.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAction "id:900110,phase:1,nolog,pass,t:none,setvar:tx.inbound_anomaly_score_threshold=6"
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.identifier }}
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/server-snippet: |
        allow 51.149.249.0/27;
        allow 51.149.249.32/27;
        allow 51.149.250.0/24;
        allow 51.149.249.0/29:
        allow 194.33.249.0/29;
        allow 51.149.249.32/29;
        allow 194.33.248.0/29;
        allow 20.49.214.199/32;
        allow 20.49.214.228/32;
        allow 35.176.93.186/32;
        allow 18.130.148.126/32;
        allow 35.176.148.126/32;
        allow 18.169.147.172/32;
        allow 128.77.75.64/26;
        allow 51.149.251.0/24;
        allow 51.149.249.64/29;
        allow 194.33.192.0/18;
        deny all;
        if ($http_spider_name ~* "crawlergo") {
          return 403;
        }
spec:
  ingressClassName: modsec
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "laa-court-data-ui.fullName" . }}-service
                port:
                  number: 80
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: {{ .Values.cert }}
