apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "laa-court-data-ui.fullName" . }}-app-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laa-court-data-ui.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAction "id:900110,phase:1,nolog,pass,t:none,setvar:tx.inbound_anomaly_score_threshold=6"
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.identifier }}
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: modsec
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "laa-court-data-ui.fullName" . }}-service
                port:
                  number: 80
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: {{ .Values.cert }}
