apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: laa-court-data-ui-app-ingress
  namespace: laa-court-data-ui-uat
spec:
  rules:
    - host: uat.view-court-data.service.justice.gov.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: laa-court-data-ui-app-service
              servicePort: 80
  tls:
    - hosts:
      - uat.view-court-data.service.justice.gov.uk
      secretName: laa-court-data-ui-uat-cert
