# frozen_string_literal: true

require_relative 'court_data_adaptor/configuration'
require_relative 'court_data_adaptor/configurable'
require_relative 'court_data_adaptor/client'
require_relative 'court_data_adaptor/errors'
require_relative 'court_data_adaptor/acts_as_resource'
require_relative 'court_data_adaptor/resource/base'
require_relative 'court_data_adaptor/resource/prosecution_case'
require_relative 'court_data_adaptor/resource/hearing_summary'
require_relative 'court_data_adaptor/resource/hearing'
require_relative 'court_data_adaptor/resource/hearing_event'
require_relative 'court_data_adaptor/resource/provider'
require_relative 'court_data_adaptor/resource/cracked_ineffective_trial'
require_relative 'court_data_adaptor/resource/defendant'
require_relative 'court_data_adaptor/resource/offence'
require_relative 'court_data_adaptor/resource/laa_reference'
require_relative 'court_data_adaptor/resource/court_application'
require_relative 'court_data_adaptor/resource/court_application_type'
require_relative 'court_data_adaptor/resource/court_application_party'
require_relative 'court_data_adaptor/resource/judicial_result'
require_relative 'court_data_adaptor/resource/mode_of_trial_reason'
require_relative 'court_data_adaptor/resource/plea'
require_relative 'court_data_adaptor/query/base'
require_relative 'court_data_adaptor/query/defendant/reference_parser'
require_relative 'court_data_adaptor/query/defendant/by_uuid'
