# frozen_string_literal: true

require_relative 'court_data_adaptor/configuration'
require_relative 'court_data_adaptor/configurable'
require_relative 'court_data_adaptor/client'
require_relative 'court_data_adaptor/resource/base'
require_relative 'court_data_adaptor/resource/error'
require_relative 'court_data_adaptor/resource/queryable'
require_relative 'court_data_adaptor/resource/prosecution_case'
require_relative 'court_data_adaptor/resource/defendant'
require_relative 'court_data_adaptor/query/base'
require_relative 'court_data_adaptor/query/defendant/by_name'
require_relative 'court_data_adaptor/query/defendant/by_reference'
require_relative 'court_data_adaptor/query/defendant/reference_parser'
require_relative 'court_data_adaptor/query/prosecution_case'
require_relative 'court_data_adaptor/name_parser'
