---
  - "0: None or unknown"
  - "Address of youth on supervision order"
  - "Adjournment"
  - "Adjournment (enforcement case)"
  - "Adjournment (No Notice)"
  - "Adjournment reason:"
  - "Adjournment reasons"
  - "Adjournment refused"
  - "Adult remittal for sentence - Adjournment"
  - "An attachment of earnings order"
  - "Anti-social behaviour injunction transferred"
  - "Anti-social behaviour order varied"
  - "Appeal against conviction allowed"
  - "Appeal against conviction and sentence dismissed"
  - "Appeal against conviction dismissed"
  - "Appeal against conviction dismissed and sentence varied"
  - "Appeal against sentence allowed"
  - "Appeal against sentence dismissed"
  - "Appeal withdrawn"
  - "Application refused"
  - "Application to vacate granted"
  - "Appointment for the Purpose of Cross Examination"
  - "Bail granted conditionally pending appeal to the Court of Appeal Criminal Division"
  - "Bail reviewed - conditions varied or imposed"
  - "Case part heard"
  - "Case reopened"
  - "Certificate of conviction under Section 232A of the Criminal Justice Act 2003 / Section 310 of the Sentencing Act 2020"
  - "Clamping order (non payment of criminal legal aid)"
  - "Closure order"
  - "Closure order extended"
  - "Committed to Crown Court for Sentence - corporation"
  - "Committed to Crown Court for sentence - in custody with bail direction"
  - "Committed to Crown Court for sentence in custody"
  - "Committed to Crown Court for sentence in hospital for Restriction Order"
  - "Committed to Crown Court for sentence in prison for restriction order"
  - "Committed to Crown Court for sentence in Youth Detention Accommodation"
  - "Committed to Crown Court for sentence on conditional bail"
  - "Committed to Crown Court for sentence on unconditional bail"
  - "Committed to the Crown Court in custody for consideration of the question of bail in a charge of murder"
  - "Community order amended"
  - "Compensation against LA- Notice"
  - "Conditional discharge (no notice produced)"
  - "Confiscation"
  - "Confiscation order"
  - "Confiscation order discharged"
  - "Confiscation order where Court does not decide the available amount"
  - "Contempt of court findings"
  - "Conviction quashed"
  - "Corporation sent to Crown Court for trial"
  - "Costs"
  - "Costs to Crown Prosecution Service"
  - "Count quashed"
  - "COVID-19 pandemic impacts"
  - "Criminal behaviour order"
  - "Criminal behaviour order until further order"
  - "Criminal behaviour order variation"
  - "Dealt with at away Court"
  - "Dealt with on behalf of other Court"
  - "Defendant committed suicide"
  - "Defendant has died"
  - "Defendant's costs payable from central funds  - sum to be assessed"
  - "Defendant's details changed"
  - "Deferred sentence"
  - "Direction made under section 36 of the Youth Justice and Criminal Evidence Act 1999 that the accused shall not cross examine the following witness in person"
  - "Discharged"
  - "Disclosure order"
  - "Discontinued"
  - "Dismissed"
  - "Dismissed - proceedings deemed a nullity"
  - "Dismissed (civil matter)"
  - "Dismissed (no appearance by informant)"
  - "Dismissed (No evidence offered)"
  - "Enforcement warrant with bail (dated)"
  - "Enforcement warrant with bail (undated)"
  - "Enforcement warrant without bail"
  - "Engagement and support order"
  - "Equivocal plea"
  - "For a bail application to be made"
  - "For a case management hearing (must attend)"
  - "For a case management hearing (no need to appear)"
  - "For a Newton hearing"
  - "For a pre-sentence report to be prepared"
  - "For legal advice or representation"
  - "For service of Section 9 witness statements"
  - "Forfeiture order (cash)"
  - "Further review of court order"
  - "Guilty plea taken into account"
  - "Hearsay direction"
  - "Hospital direction and limitation direction"
  - "Hospital order"
  - "Indictment quashed"
  - "Indictment to remain on file"
  - "Insufficient court time to hear the case"
  - "Interim criminal behaviour order made until further order"
  - "Interim hospital order"
  - "Interim hospital order extended"
  - "Interim sexual harm prevention order"
  - "Interim sexual risk order"
  - "Interim slavery and trafficking prevention order"
  - "Interim slavery and trafficking risk order"
  - "Legal Aid Appeal Granted"
  - "Legal Aid Appeal Refused"
  - "Legal Aid Representation Varied"
  - "Legal Aid Representation Varied (Crown Court)"
  - "Legal Aid Transfer Granted"
  - "Legal Aid Transfer Refused"
  - "Legal Aid Withdrawn"
  - "Mention at conclusion"
  - "Next hearing"
  - "Next hearing in Crown Court"
  - "No compensation reason"
  - "No evidence offered - verdict of not guilty by order of Judge"
  - "No evidence offered (summary offence in the Crown Court)"
  - "No further action taken in respect of conduct (contempt)"
  - "No order for costs"
  - "No video link reason"
  - "Offence not on indictment"
  - "Order"
  - "Order discharged"
  - "Order for remittal of a civil debt"
  - "Other party's costs from central funds - sum assessed"
  - "Other party's costs from central funds - sum to be assessed"
  - "Present yourself"
  - "Prosecutor's costs from central funds - sum assessed"
  - "Prosecutor's costs from central funds - sum to be assessed"
  - "Racially aggravated offence"
  - "Racially and religiously aggravated offence"
  - "Reasons"
  - "Remand in Youth Detention Accommodation"
  - "Remand on own Recognisance"
  - "Remanded in custody"
  - "Remanded on conditional bail"
  - "Restraining order discharged"
  - "Restraining order varied"
  - "Ruling"
  - "Sent to Crown Court for trial"
  - "Sent to Crown Court for trial - Corporation"
  - "Sent to Crown Court for trial and transfer direction to Hospital"
  - "Sent to Crown Court for trial in custody"
  - "Sent to Crown Court for trial in Local Authority Accommodation"
  - "Sent to Crown Court for trial in youth detention accommodation"
  - "Sent to Crown Court for trial on conditional bail"
  - "Sent to Crown Court for trial on unconditional bail"
  - "Sent to Crown Court in custody for trial with bail direction"
  - "Sentence at conclusion"
  - "Sentence varied"
  - "Serious terrorism sentence of imprisonment (S.282A SA 2020)"
  - "Sexual harm prevention order renewed"
  - "Sexual harm prevention order varied"
  - "Sexual risk order"
  - "Sexual risk order varied"
  - "Slavery and trafficking prevention order"
  - "Slavery and trafficking prevention order made on application"
  - "Slavery and trafficking prevention order varied"
  - "Slavery and Trafficking Reparation Order"
  - "Slavery and trafficking risk order"
  - "Special measures"
  - "Special measures direction: A video recording be admitted of the evidence in chief of the interview"
  - "Special measures direction: A video recording is not to be admitted because the requirements for its admission have not been complied with"
  - "Special measures direction: The examination is to be conducted through an intermediary"
  - "Special measures direction: The recording must be made in the presence of specified person(s)"
  - "Special measures direction: Wigs and gowns shall not be worn for the duration of the evidence of a specified witness"
  - "Special measures direction: Witness be prevented from seeing the defendant by means of a screen"
  - "Special measures direction: Witness be prevented from seeing the defendant by specified means"
  - "Special measures direction: Witness to be provided with an aid to commumication"
  - "Special measures direction: Witness to give evidence by means of a live link"
  - "Special measures direction: Witness to give evidence in private"
  - "Summons on referral to other court"
  - "Surcharge remitted"
  - "Suspended sentence order of detention amended"
  - "Suspended sentence order of detention amended - supervising court or operational period or supervision period"
  - "Suspended sentence order of imprisonment  amended"
  - "Suspended sentence order of imprisonment  amended - supervising court or operational period or supervision period"
  - "Text"
  - "The case is not before this court"
  - "The court decided that"
  - "The Court did not proceed with the trial in the defendant's absence"
  - "The court directs that evidence relating to the bad character of the defendant be admitted in the proceedings"
  - "The court gives leave for evidence of the bad character of a person to be admitted in the proceedings"
  - "The court will review this order"
  - "The new and amended requirements are"
  - "Third Party Costs"
  - "To attend or a warrant to issue"
  - "To attend or to return the plea form sent with the summons"
  - "To plead guilty or not guilty to the offence(s)"
  - "To produce a medical certificate"
  - "To tie up with other cases"
  - "Total custodial period"
  - "Transfer to another Crown Court"
  - "Unable to proceed with case on the Common Platform, entered into Libra"
  - "Undertakings given"
  - "Unexpected circumstances meant that the case could not be heard"
  - "Warrant for arrest on complaint with bail (dated)"
  - "Warrant for arrest on complaint with bail (undated)"
  - "Warrant for arrest on complaint without bail"
  - "Warrant for arrest redated"
  - "Warrant for arrest with bail (dated)"
  - "Warrant for arrest with bail (undated)"
  - "Warrant for arrest without bail"
  - "Warrant for arrest without bail executed on day of issue"
  - "Warrant not executed"
  - "Warrant of arrest without bail on sentence of imprisonment in absence"
  - "Warrant withdrawn"
  - "Wasted costs order - defendant to pay"
  - "Wasted costs order - Prosecutor to pay"
  - "Wasted Costs Order Solicitor to Pay"
  - "Where closure order is in under Anti-social Behaviour, Crime and Policing Act 2014"
  - "Where closure order is under Sexual Offences Act 2003"
  - "Withdrawn"
  - "Withdrawn (notice produced)"
  - "Withdrawn (recharge at named Court)"
  - "Withdrawn (recharge at unnamed Court)"
  - "Withdrawn in favour of another offence"
  - "Witness summons"
  - "Youth remittal - Adjournment"
