apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: laa-court-data-ui-app-ingress
  namespace: laa-court-data-ui-dev
  annotations:
  nginx.ingress.kubernetes.io/server-snippet: |
    location / {
      deny 223.178.211.9;
      deny 143.244.161.10;
      deny 206.72.194.213;
    }
spec:
  rules:
    - host: dev.view-court-data.service.justice.gov.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: laa-court-data-ui-app-service
              servicePort: 80
  tls:
    - hosts:
      - dev.view-court-data.service.justice.gov.uk
      secretName: laa-court-data-ui-dev-cert
