namespace: laa-court-data-ui-staging
replicas:
  worker: 2
  web: 4
image:
  tag: ""
  repository: "nginx"
env: staging
host: staging.view-court-data.service.justice.gov.uk
cdaHost: https://test.court-data-adaptor.service.justice.gov.uk/api/internal/v1
googleAnalyticsId: 'UA-131160087-16'
displayRawResponses: enabled
identifier: laa-court-data-ui-app-ingress-laa-court-data-ui-staging-green
cert: laa-court-data-ui-staging-cert
